### ISSUE TITLE
"Unable to find pacts for given provider" when working with pact_broker-docker

### ISSUE THREAD

**Issue by lirantal** [pact-foundation/pact-node#120]
## Software versions

-   **OS**: Mac OSX 10.12.6 
-   **Docker version**: 17.09.0-ce, build afdb6d4

## Expected behaviour

Provider testing is able to pull and very pacts from the broker.

## Actual behaviour

"Unable to find pacts for given provider"  during a provider's testing verification:

```js
    let opts = {
      provider: 'Reviews',
      providerBaseUrl: 'http://localhost:3002/',
      providerStatesSetupUrl: 'http://localhost:4011/setup/',
      pactBrokerUrl: 'http://localhost:88',
      tags: ['develop'],
      providerVersion: "1.0.0"
    }

    return new Verifier().verifyProvider(opts)
      .then(output => {
        console.log('Pact Verification Complete!')
        console.log(output)
      })
```

## Steps to reproduce

1. Clone the pact_broker-docker repository
2. Adjust the nginx config for non-SSL
3. Run docker-compose up

## Relevant log files

Setting PACT_BROKER_LOG_LEVEL to INFO for the pact_broker service in docker-compose.yml doesn't yield anything useful. Setting it to DEBUG I do see that it "works", querying the DB etc, but nothing informational about processing the request.

**Comment by lirantal** [comment]
Update: this might be a non-issue or a very bigger one, depends how you look at it :-)

I used the configuration for the hosted pact broker on dius and I'm still getting the same error with unable to find pacts for the given provider.

**Comment by mefellows** [comment]
Might need a reproduceable code base Liran, I just tested the following configuration successfully:

docker-compose.yml
```yaml
version: '3'

services:

  postgres:
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  broker_app:
    image: dius/pact-broker
    ports:
      - "80:80"
    links:
      - postgres
    environment:
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres

```
Then ran the following:

```
# modify e2e publish.js and provider.spec.js to update broker to http://localhost
# See code here: https://github.com/pact-foundation/pact-js/tree/repro/issue-120
docker-compose up -d
npm run  test:e2e-examples
```

Head over to http://localhost in the browser and you should see:

<img width="713" alt="screenshot" src="https://user-images.githubusercontent.com/53900/46606145-8e944b80-cb47-11e8-8f0b-a21850f9cc1e.png">

**Comment by lirantal** [comment]
so that's over HTTP?
I'll try to get a working example.

Any ideas what else can I look at?

**Comment by mefellows** [comment]
Yep, I removed nginx as it's not necessary (just convenient if you want to test SSL etc.). You can pretty much leave nginx there and just hit port 80 instead. It _should_ still work.

I also note that you're hitting port `88`, -have you mapped it to port `80` on the container by any chance? If so, this won't work due to some interesting Rack challenges. That might also be why you're running into issues on the http side (see https://github.com/DiUS/pact_broker-docker#notes).

**Comment by mefellows** [comment]
Just for posterity, if you want to run a reverse proxy in front of the broker, read [this](https://github.com/pact-foundation/pact_broker/wiki/Configuration#running-the-broker-behind-a-reverse-proxy)

**Comment by mefellows** [comment]
And to make it easier for those in the future, I just updated the compose file in that sample repository to avoid confusion - now nginx fronts both http and ssl:

https://github.com/DiUS/pact_broker-docker/commit/5b0ebca03431316774ecd61f2fa1d83977b277dd

**Comment by lirantal** [comment]
Port 88 is for the nginx conf, i.e:
```
  nginx:
    image: nginx:alpine
    links:
      - broker_app:broker
    volumes:
    - ./ssl/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./ssl:/etc/nginx/ssl
    ports:
    - "88:443"
```

Needed because I had something else occupying 443 already.

😄 Ok so working with the broker directly instead of nginx worked out just fine.
Indeed probably worth a doc or that example you posted to be made clearer, probably in the pact-broker repo.

We can close the issue.
